import { Cable, Translation, StandardStructure } from './types';

export const CABLE_DATABASE: Cable[] = [];

export const STANDARD_STRUCTURES: StandardStructure[] = [];

export const TRANSLATIONS: Translation = {
  title: 'CableFill Calculator',
    nav: {
      dashboard: 'Pannello',
      trays: 'Passerelle',
      conduits: 'Tubazioni',
      cables: 'Database Cavi',
      admin: 'AMMINISTRAZIONE',
      users: 'Gestione Utenti',
      newProject: 'Nuovo Progetto',
    },
    sidebar: {
      overview: 'PANORAMICA',
      cableTrays: 'PASSERELLE',
      conduits: 'TUBI PROTETTIVI',
      cables: 'CAVI',
      database: 'BANCO PROGETTI',
      vault: 'ARCHIVIO',
      documentation: 'DOCUMENTAZIONE',
      projectManagement: 'Project Hub',
      appSubtitle: 'SISTEMA DI INGEGNERIA',
      userTitle: 'PROPRIETÀ PRIVATA',
    },
    header: {
      currentModule: 'Modulo Corrente',
      searchPlaceholder: 'CERCA PARAMETRI DI ANALISI...',
      lightMode: 'Chiaro',
      darkMode: 'Scuro',
      export: 'ESPORTA',
      exportPdf: 'ESPORTA COME PDF (.pdf)',
      exportCsv: 'ESPORTA COME EXCEL (.csv)',
      generatingPdf: 'GENERAZIONE PDF...',
    },
    input: {
      parameters: 'PARAMETRI DI INPUT',
      structureName: 'NOME STRUTTURA',
      structureType: 'TIPO DI STRUTTURA',
      dimensions: 'DIMENSIONI (mm)',
      fillLimit: 'LIMITE DI RIEMPIMENTO (%)',
      addCable: 'AGGIUNGI CAVO',
      calculate: 'ESEGUI CALCOLO',
      width: 'Larghezza',
      height: 'Altezza',
      quantity: 'Qtà',
      standardSize: 'DIMENSIONE STANDARD',
      customSize: 'PERSONALIZZATO / ALTRO',
      diameter: 'DIAMETRO',
      size: 'DIMENSIONE (mmq)',
      tagPlaceholder: 'TAG / CIRCUITO (ES: C1, LUCE...)',
      editTag: 'MODIFICA TAG...',
      hasSeparator: 'USA SETTO SEPARATORE',
      spareTubes: 'TUBI DI RISERVA',
      mixedSystemsWarning: 'CAVI POTENZA E DATI RICHIEDONO UN SETTO NELLE PASSERELLE.',
      conduitMixedWarning: 'PROIBITO MISCHIARE POTENZA E DATI NEI TUBI PROTETTIVI.',
      separatorRequiredWarning: 'NON È POSSIBILE DISATTIVARE IL SETTO: SONO PRESENTI SIA CAVI POTENZA CHE SISTEMI SPECIALI. RIMUOVERE PRIMO UN TIPO DI SISTEMA.',
      clearAll: 'PULISCI TUTTO',
      cableAdded: 'Cavo aggiunto',
      cableRemoved: 'Cavo rimosso',
      allCablesRemoved: 'Tutti i cavi rimossi',
      searchCables: 'CERCA CAVI...',
      favorites: 'PREFERITI',
      notes: 'NOTE DEL PROGETTO',
      notesPlaceholder: 'Inserire note tecniche, premesse di calcolo o osservazioni del progetto...',
    },
    results: {
      utilization: 'UTILIZZO',
      status: 'STATO GLOBALE',
      pass: 'SUPERATO',
      fail: 'FALLITO',
      totalArea: 'AREA TOTALE',
      usedArea: 'AREA UTILIZZATA',
      numberOfTrays: 'STRUTTURE NECESSARIE',
      autoScaled: 'AUTO-SCALATO',
      deltaMax: 'DELTA MAX',
      allow: 'LIMITE',
    },
    preview: {
      structuralPreview: 'ANTEPRIMA STRUTTURALE',
      crossSection: 'SEZIONE TRASVERSALE',
      cableSchedule: 'TABELLA CAVI / CORRISPONDENZA',
      noTag: 'SENZA TAG',
      noCables: 'Nessun cavo ancora aggiunto al progetto.',
      noSavedProjects: 'Nessun progetto salvato trovato.',
      structure: 'STRUTTURA',
      limit: 'LIMITE',
      utilization: 'UTILIZZO',
      reset: 'RESET PROGETTO',
      newProject: 'NUOVO PROGETTO',
      deleteProject: 'ELIMINA PROGETTO',
      project: 'PROGETTO',
      saveProject: 'SALVA PROGETTO',
      savedProjects: 'PROGETTI SALVATI',
      loadProject: 'CARICA PROGETTO',
      lastSaved: 'ULTIMO SALVATAGGIO',
      mustBeLoggedIn: 'Devi aver effettuato l\'accesso per salvare i progetti.',
      saveError: 'Errore durante il salvataggio del progetto',
      unexpectedError: 'Errore imprevisto durante il salvataggio del progetto',
      pdfExportError: 'Errore durante l\'esportazione del PDF',
      zoomIn: 'Aumenta Zoom',
      zoomOut: 'Riduci Zoom',
      fitToScreen: 'Adatta allo Schermo',
      dashboard: 'Pannello Principale',
      shortcuts: 'Scorciatoie',
    },
    management: {
      addNew: 'AGGIUNGI NUOVO MODELLO',
      name: 'NOME MODELLO',
      width: 'LARGHEZZA (mm)',
      height: 'ALTEZZA (mm)',
      diameter: 'DIAMETRO (mm)',
      weight: 'PESO (kg/km)',
      type: 'TIPO',
      category: 'CATEGORIA',
      power: 'POTENZA',
      specialSystems: 'SISTEMI SPECIALI (DATI/SICUREZZA)',
      actions: 'AZIONI',
      save: 'SALVA MODELLO',
      cancel: 'ANNULLA',
      delete: 'ELIMINA',
      edit: 'MODIFICA',
      existingModels: 'MODELLI ESISTENTI NEL DATABASE',
      existingCables: 'CAVI ESISTENTI NEL DATABASE',
      saveSuccess: 'Modello salvato con successo!',
      deleteSuccess: 'Modello eliminato con successo!',
      confirmDelete: 'Sei sicuro di voler eliminare questo modello?',
    },
    auth: {
      login: 'LOGIN',
      register: 'REGISTRAZIONE',
      username: 'NOME UTENTE',
      password: 'PASSWORD',
      signIn: 'ACCEDI',
      signUp: 'RICHIEDI ACCESSO',
      needAccount: 'Non hai un account? Richiedi l\'accesso',
      haveAccount: 'Hai già um account? Accedi qui',
      adminPanel: 'PANNELLO ADMIN',
      logout: 'LOGOUT',
      pendingApproval: 'Il tuo account è in attesa di approvazione da parte di un amministratore.',
      connectionError: 'Errore di connessione al server.',
      email: 'EMAIL',
      name: 'NOME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'La password è obbligatoria.',
    },
    userManagement: {
      title: 'GESTIONE UTENTI',
      users: 'UTENTI',
      approve: 'APPROVA',
      delete: 'ELIMINA',
      status: 'STATO',
      approved: 'APPROVATO',
      pending: 'IN ATTESA',
      role: 'RUOLO',
      confirmDelete: 'Sei sicuro di voler eliminare questo utente?',
      createError: 'Errore durante la creazione dell\'utente',
      fetchError: 'Errore durante il recupero degli utenti',
      approveError: 'Errore durante l\'approvazione dell\'utente',
      updateError: 'Errore durante l\'aggiornamento dell\'utente',
      deleteError: 'Errore durante l\'eliminazione dell\'utente',
      unknownError: 'Errore sconosciuto',
      userCreated: 'Utente creato con successo!',
      userApproved: 'Utente approvato con successo!',
      userDeleted: 'Utente eliminato con successo!',
      changesSaved: 'Modifiche salvate con successo!',
      newUser: 'Nuovo Utente',
      searchPlaceholder: 'Cerca per nome o email...',
      allRoles: 'Tutti i Ruoli',
      createNewUser: 'Crea Nuovo Utente',
      nameLabel: 'Nome',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      passwordRequired: 'La password è obbligatoria.',
      accessLevel: 'Livello di Accesso',
      accessibleModules: 'Moduli Accessibili',
      cancel: 'Annulla',
      creating: 'Creazione...',
      createUser: 'Crea Utente',
      nameHeader: 'NOME',
      emailHeader: 'EMAIL',
      levelHeader: 'LIVELLO',
      modulesHeader: 'MODULI',
      statusHeader: 'STATO',
      actionsHeader: 'AZIONI',
      noUsersFound: 'Nessun utente trovato',
      adjustFilters: 'Prova a regolare la ricerca o i filtri.',
      dbColumns: 'COLONNE DEL DATABASE',
      masterAdminDeleteError: "L'amministratore master non può essere eliminato.",
      adminRole: 'Amministratore',
      userRole: 'Utente',
      cableFillPro: 'CableFill Pro',
    },
    report: {
      title: 'RAPPORTO DI CONFORMITÀ',
      crossSection: 'VISTA IN SEZIONE (CROSS-SECTION)',
      scale: 'SCALA 1:5',
      parameters: 'PARAMETRI DI CALCOLO',
      totalArea: 'Area Totale Passerella (A_tray)',
      usedArea: 'Area Occupata Cavi (Σ A_cables)',
      reserveFactor: 'Fattore di Riserva',
      formula: 'FORMULA DI OCCUPAZIONE',
      finalResult: 'RISULTATO FINALE',
      occupancyRate: 'TASSO DI OCCUPAZIONE',
      approved: 'APPROVATO',
      rejected: 'RESPINTO',
      cableManifest: 'ELENCO CAVI',
      total: 'TOTALE',
      units: 'UNITÀ',
      specification: 'SPECIFICA',
      dimension: 'DIMENSIONE',
      tag: 'TAG',
      qty: 'QTÀ',
      printPDF: 'STAMPA PDF',
      projectId: 'ID PROGETTO',
      client: 'CLIENTE',
      engineer: 'ING. RESPONSABILE',
      emissionDate: 'DATA EMISSIONE',
      digitalSignature: 'Firma Digitale',
      verificationHash: 'HASH DI VERIFICA',
      generatedAt: 'Generato il',
    },
    misc: {
      techNotes: 'Osservazioni tecniche',
      occupancyDist: 'Distribuzione Occupazione',
      keyboardShortcuts: 'Scorciatoie da Tastiera',
      increaseProductivity: 'Aumenta la tua produttività',
      reportPreview: 'ANTEPRIMA DEL RAPPORTO',
      widthShort: 'L',
      heightShort: 'H',
      addCablesPrompt: 'Aggiungi cavi usando il modulo sopra.',
      understood: 'Capito',
      saveProjectShortcut: 'Salva Progetto',
      newProjectShortcut: 'Nuovo Progetto',
      closeModalsShortcut: 'Chiudi Modal / Reset Zoom',
    },
    cableTypes: {
      power: 'Potenza',
      data: 'Dati',
      evac: 'EVAC',
      irai: 'IRAI',
    },
};
